local mt = {}

-- 攻击类型
ATTACK_TYPE = {
    -- 法术
    NORMAL = ATTACK_TYPE_NORMAL,
    --
    MELEE = ATTACK_TYPE_MELEE,
    PIERCE = ATTACK_TYPE_PIERCE,
    SIEGE = ATTACK_TYPE_SIEGE,
    MAGIC = ATTACK_TYPE_MAGIC,
    CHAOS = ATTACK_TYPE_CHAOS,
    HERO = ATTACK_TYPE_HERO
}

-- 伤害类型
DAMAGE_TYPE = {
    -- 未知的
    UNKNOWN = DAMAGE_TYPE_UNKNOWN,
    NORMAL = DAMAGE_TYPE_NORMAL,
    ENHANCED = DAMAGE_TYPE_ENHANCED,
    FIRE = DAMAGE_TYPE_FIRE,
    COLD = DAMAGE_TYPE_COLD,
    LIGHTNING = DAMAGE_TYPE_LIGHTNING,
    POISON = DAMAGE_TYPE_POISON,
    DISEASE = DAMAGE_TYPE_DISEASE,
    DIVINE = DAMAGE_TYPE_DIVINE,
    MAGIC = DAMAGE_TYPE_MAGIC,
    SONIC = DAMAGE_TYPE_SONIC,
    ACID = DAMAGE_TYPE_ACID,
    FORCE = DAMAGE_TYPE_FORCE,
    DEATH = DAMAGE_TYPE_DEATH,
    MIND = DAMAGE_TYPE_MIND,
    PLANT = DAMAGE_TYPE_PLANT,
    DEFENSIVE = DAMAGE_TYPE_DEFENSIVE,
    DEMOLITION = DAMAGE_TYPE_DEMOLITION,
    SLOW_POISON = DAMAGE_TYPE_SLOW_POISON,
    SPIRIT_LINK = DAMAGE_TYPE_SPIRIT_LINK,
    SHADOW_STRIKE = DAMAGE_TYPE_SHADOW_STRIKE,
    UNIVERSAL = DAMAGE_TYPE_UNIVERSAL
}

-- 武器类型
WEAPON_TYPE = {
    WHOKNOWS = WEAPON_TYPE_WHOKNOWS,
    METAL_LIGHT_CHOP = WEAPON_TYPE_METAL_LIGHT_CHOP,
    METAL_MEDIUM_CHOP = WEAPON_TYPE_METAL_MEDIUM_CHOP,
    METAL_HEAVY_CHOP = WEAPON_TYPE_METAL_HEAVY_CHOP,
    METAL_LIGHT_SLICE = WEAPON_TYPE_METAL_LIGHT_SLICE,
    METAL_MEDIUM_SLICE = WEAPON_TYPE_METAL_MEDIUM_SLICE,
    METAL_HEAVY_SLICE = WEAPON_TYPE_METAL_HEAVY_SLICE,
    METAL_MEDIUM_BASH = WEAPON_TYPE_METAL_MEDIUM_BASH,
    METAL_HEAVY_BASH = WEAPON_TYPE_METAL_HEAVY_BASH,
    METAL_MEDIUM_STAB = WEAPON_TYPE_METAL_MEDIUM_STAB,
    METAL_HEAVY_STAB = WEAPON_TYPE_METAL_HEAVY_STAB,
    WOOD_LIGHT_SLICE = WEAPON_TYPE_WOOD_LIGHT_SLICE,
    WOOD_MEDIUM_SLICE = WEAPON_TYPE_WOOD_MEDIUM_SLICE,
    WOOD_HEAVY_SLICE = WEAPON_TYPE_WOOD_HEAVY_SLICE,
    WOOD_LIGHT_BASH = WEAPON_TYPE_WOOD_LIGHT_BASH,
    WOOD_MEDIUM_BASH = WEAPON_TYPE_WOOD_MEDIUM_BASH,
    WOOD_HEAVY_BASH = WEAPON_TYPE_WOOD_HEAVY_BASH,
    WOOD_LIGHT_STAB = WEAPON_TYPE_WOOD_LIGHT_STAB,
    WOOD_MEDIUM_STAB = WEAPON_TYPE_WOOD_MEDIUM_STAB,
    CLAW_LIGHT_SLICE = WEAPON_TYPE_CLAW_LIGHT_SLICE,
    CLAW_MEDIUM_SLICE = WEAPON_TYPE_CLAW_MEDIUM_SLICE,
    CLAW_HEAVY_SLICE = WEAPON_TYPE_CLAW_HEAVY_SLICE,
    AXE_MEDIUM_CHOP = WEAPON_TYPE_AXE_MEDIUM_CHOP,
    ROCK_HEAVY_BASH = WEAPON_TYPE_ROCK_HEAVY_BASH
}

-- 单位伤害目标
function mt.damageTarget(unit, enemy, harm, attack, ranged, attackType, damageType, weaponType)
    local attack = attack or false -- 默认不是攻击伤害
    local ranged = ranged or false -- 默认不是远程攻击伤害
    local attackType = attackType or ATTACK_TYPE.NORMAL
    local damageType = damageType or DAMAGE_TYPE.NORMAL
    local weaponType = weaponType or WEAPON_TYPE.WHOKNOWS
    UnitDamageTarget(unit, enemy, harm, attack, ranged, attackType, damageType, weaponType)
end

-- 单位伤害区域
function mt.damageArea(unit, delay, radius, x, y, harm, attack, ranged, attackType, damageType, weaponType)
    local attack = attack or false -- 默认不是攻击伤害
    local ranged = ranged or false -- 默认不是远程攻击伤害
    local attackType = attackType or ATTACK_TYPE.NORMAL
    local damageType = damageType or DAMAGE_TYPE.NORMAL
    local weaponType = weaponType or WEAPON_TYPE.WHOKNOWS
    UnitDamagePoint(unit, delay, radius, x, y, harm, attack, ranged, attackType, damageType, weaponType)
end

return mt
