
gTrg = require 'types.trigger'
gP = require 'types.player'
gU = require 'types.unit'
gH = require 'types.hero'
gAbi = require 'types.ability'
gT = require 'types.timer'
gRect = require 'types.rect'
gCamera = require 'types.camera'
gFog = require 'types.fogmodifier'
gSound = require 'types.sound'
gDia = require 'types.dialog'
gGame = require 'types.game'
gGroup = require 'types.group'
gEff = require 'types.effect'
gTag = require 'types.texttag'
gDmb = require 'types.board'
gDam = require 'types.damage'
