gTrg.RegAnyPlayerUnitEvent(EVENT_PLAYER_UNIT.SELECTED, function()
    local trgU = GetTriggerUnit()
    -- local mj = gU.create(Player(0), 'yhmj', gU.getXY(trgU))
    -- local abiId = 'AUfa'
    -- gAbi.add(mj, abiId)
    -- gAbi.setDataReal(mj, abiId, 1, ABILITY_DATA.DATA_B, 10.00)
    -- gAbi.setDataReal(mj, abiId, 1, ABILITY_DATA.DATA_A, 5.00)
    -- gU.issueOrderTar(mj, 'frostarmor', trgU)
    --printF(gU.getMoveSpeed(trgU),gU.getDefaultMoveSpeed(trgU))
end)
