
local log = CreateFogModifierRect(GetTriggerPlayer(), FOG_OF_WAR_VISIBLE, g.gg_rct_TheMainBase, true, false)
FogModifierStart(log)
-- 设置玩家可用地图区域=默认可用地图区域
SetCameraBoundsToRectForPlayerBJ(GetTriggerPlayer(), GetPlayableMapRect())
PlayMusic()
Rect()
GetCameraMargin()
IsUnitDeadBJ()
YhDistanceCoordinate()
IsUnitDeadBJ()
ConvertUnitState()
AdjustUnitStateBJ()
BlzGetUnitArmor()
BlzGetTriggerPlayerMouseY()
SuspendHeroXP()
GetUnitsInRectAll(mt.lgf1)
GroupEnumUnitsInRect(g, r, filter)
SetUnitFlyHeight()
EXGetAbilityDataReal()
EXGetUnitAbility()
SetHeroStr()
GetHeroInt()
CountUnitsInGroup()
UnitId2String()
EXSetItemDataString()
SetItemVisible()
ChooseRandomItemEx()
